### ISSUE TITLE
Support Outlook

### ISSUE THREAD

**Issue by BrenuDev** [mobizt/ESP32-Mail-Client#15]
Hi!

I'm trying to get it working with my outlook account.
But I get every time this error.

[E][ssl_client.cpp:33] handle_error(): SSL - An invalid SSL record was received
[E][ssl_client.cpp:35] handle_error(): MbedTLS message code: -29184
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -29184
Error, could not connect to server
Error sending Email, could not connect to server

Using the following settings
![image](https://user-images.githubusercontent.com/8317833/62297243-29f90300-b471-11e9-8400-52c6ff97ac81.png)
Is this an issue with this library or certificate related?
Thanks!

**Comment by mobizt** [comment]
This is the issue at the beginning of making the library.

This due to many SMTP servers included Outlook.com use **STARTTLS** or **explicit TLS** protocol on port 587 which required client to send **STARTTLS** command before perform SSL handshake. 

Gmail also support STARTTLS on port 587 and due to we set the option to enable **"less secure apps"** to allow client to connect via SSL port 465.

The WiFi client used by this library need to rewrite to support STARTTLS and may be available on the future update.

**Comment by BrenuDev** [comment]
Ok thanks! For the info.
Really looking forward to the update.
It's the final piece of my code to be functional.

**Comment by mobizt** [comment]
The new version, v 1.2.0 was available to update. Now support STARTTLS protocol.
