### ISSUE TITLE
Request: Make it useable with other clients like TinyGSM

### ISSUE THREAD

**Issue by kugelkopf123** [mobizt/ESP32-Mail-Client#22]
Hey... thats not an issue. Its more an request. Isnt to make it useable with different clients, others than the WiFi one? 
ArduinoHTTPClient has a nice solution for that. Perhaps thats interesting for you.

https://github.com/arduino-libraries/ArduinoHttpClient/blob/master/src/HttpClient.h

**Comment by mobizt** [comment]
Thanks for your info. The important is the SSL/TLS provider for secure data encryption/decryption, handle the SSL handshake instead of normal tcp/ip client. 

For WiFi101 and WiFiNiNa, I already try this for different library (Firebase) and it works for SSL connection but not sure for TLS which required for most IMAP server.

Each device that available for Arduino HTTPClient library has small ram/eeprom which not suitable for this library which uses dynamic ram to store message data and eeprom or flash for constant string.
