### ISSUE TITLE
How I can receive only new mail?

### ISSUE THREAD

**Issue by Legantmar** [mobizt/ESP32-Mail-Client#35]
Thank you Mobizt for your esp32-mail-client
I try example Receive_email, it work good
How I can receive only new mail (unread, unseen) by criteria "NEW"? please, little example
I try this:
  imapData.setFetchUID("10");
  imapData.setSearchCriteria("NEW");
  MailClient.readMail(imapData);
but I receive 10 mail (but unread is only one of them)

**Comment by mobizt** [comment]
You should use the server supported flags which comply to rfc3501.

The recent flag is available. See [this](https://serverfault.com/questions/115769/which-imap-flags-are-reliably-supported-across-most-mail-servers).

**Comment by mobizt** [comment]
Some servers are not support RECENT, NEW or OLD arguments as search criteria.

For Gmail use case, use this to get only new message that never opened.

**imapData.setSearchCriteria("UID SEARCH NOT SEEN");**

**Comment by Legantmar** [comment]
// imapData.setSearchCriteria("UID SEARCH NOT SEEN");
it didn't help me
I am use yandex mail
what does that mean? https://yadi.sk/i/tCxTofPVOGMuog

**Comment by mobizt** [comment]
That is flags that you can set to message which supported by server.

[This is](https://github.com/mobizt/ESP32-Mail-Client/blob/master/examples/Set_flag/Set_flag.ino) the example for set flags.

Unfortunately, if some server doesn't support some search criteria as state in [rfc3501](https://tools.ietf.org/html/rfc3501#section-6.4.4), you can search with date and time like the following.

**UID SEARCH  SINCE 15-Nov-2019**

Here is supported [date format](https://tools.ietf.org/html/rfc2822#section-3.3).

This **imapData.setSearchCriteria("UID SEARCH UNSEEN")** works for Gmail, is this work for yandex?

**Comment by mobizt** [comment]
Now I register the account at Yandex.com and test send email from outlook to yandex account.

For unread messages, both search criteria, **imapData.setSearchCriteria("UID SEARCH UNSEEN")** and **imapData.setSearchCriteria("UID SEARCH NOT SEEN");** work.

For recent messages, **imapData.setSearchCriteria("UID SEARCH RECENT");** works.

For new mesage, **imapData.setSearchCriteria("UID SEARCH NEW");** works.
