### ISSUE TITLE
dealing with OAUTH mailboxes

### ISSUE THREAD

**Issue by mateusz-kusmierz** [mobizt/ESP32-Mail-Client#37]
Hello!
Mobizt I appreciate you made this library, this is amazing workpiece! Thank you!

I encounter a problem: SMTP sender mailbox is on gmail server with OAUTH authorization. 
What if we can't change OAUTH to anything else? Than we can't send emails from this mailbox.

Does anybody have a walkaround to this?

Thanks.

**Comment by mobizt** [comment]
For authenticate with the Auth token, the token has its validation period which will be expired e.g in 30 minutes.

How you generate this auth token and refresh it when expired?

If you crate auth token out side ESP32 e.g by some help of other system, how you send that token to ESP32?

The authenticate can be supported by the library but another issue may occur because of it may require the consent screen to user which not available for ESP32.

I will test it and update if this is possible.

**Comment by mateusz-kusmierz** [comment]
Yes, in case of using oauth, esp32 must have output and input devices of some sort to work with oauth. 
There is a solution called "oauth for devices" that refers to devices with limited input/output (e.g. without a web browser).
Please check this: https://developers.google.com/identity/protocols/OAuth2ForDevices
It is very precisely described how it will work.

I own 'small device' that can send alert e-mails and has only 2x40 alphanumerical display and still oauth works great on this device.
It displays something like this when I try to set oauth mailbox as sender:

```
Visit https://www.google.com/device
              BHTK-DDEM
```

Then I go to this website using a smartphone or my laptop, enter this code, and immediately my 'small device' displays that log in was successful. And once I log on oauth mailbox, it keeps working forever.

**Comment by mobizt** [comment]
Even it works for email or user profile scope but It requires a lot of process i.e. post requests including user consent that requires anather client to be done.

Another works are to support the authentication SMTP extension standard rfc4648 (request and response).

I'm not confirm the plan that this option will be available on the library due to it's alternative and not work without user consent.
