### ISSUE TITLE
Error, could not handle SMTP server response (only via ethernet)

### ISSUE THREAD

**Issue by atlantisguru** [mobizt/ESP32-Mail-Client#48]
I'm using an Olimex ESP32-EVB board.
When i'm sending email via ethernet port (fix IP) i got "Error, could not handle SMTP server response" message.
Tried with multiple mail service. Credentials are all good.
With WiFi, everything OK.
I edited the ESP32_MailClient.cpp to check, whats happening. On line 1518 the expected result code  is 220, but i got -1000.

1518: if (waitSMTPResponse(smtpData) != 220)  <- here i got -1000

Connecting to SMTP server...
[DEBUG] - INFO: connecting to SMTP server...
[DEBUG] - ***** //intentionally hidden smtp server address and not relevant
[DEBUG] - 465
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - INFO: verifying peer X.509 certificate...
[DEBUG] - INFO: certificate verified
[DEBUG] - INFO: smtp server connected
SMTP server connected, wait for response...
-1000       //i printed this after line 1518
Error, could not handle SMTP server response
[DEBUG] - ERROR: could not handle SMTP server response
[DEBUG] - INFO: cleaning SSL connection
Error sending Email, could not handle SMTP server response

**Comment by mobizt** [comment]
You may need to use secure port 587.

Some SMTP servers required STARTTLS at the beginning of the connection.

Even if it works on WiFi only and failed on Ethernet, this may be the bugs or conflicts within the lwip of the ESP32 core library.

Thanks for informing the issue, but I can't investigate to the root cause which is in the core library due to I don't have Ethernet enable hardware.

You can add **Serial.print(c);** at 
https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.cpp#L2248
To check what's the response from server.

**Comment by atlantisguru** [comment]
Thank you for your help!
It seems you are right about a possible bug in ESP core library.
I found a few forum topic about why can't use Ethernet without proper WiFi connection.
