### ISSUE TITLE
Will return multiple emails 

### ISSUE THREAD

**Issue by jawilson104** [mobizt/ESP32-Mail-Client#56]
The fix you made in 2.1.2 allowed me to read an email with a specified UID with no problems.  All the information including the body of the email was returned.  I am now trying to read multiple emails and have attached the sketch I am using.  It returns all the information from all the emails correctly except for the body section of the emails.  Please let me know what is wrong with the sketch.  I would really appreciate the help.  You did a great job updating to 2.1.2.  I did try the sketch with 2.1.3 and still had the problem.
[Multiple Email Code.txt](https://github.com/mobizt/ESP32-Mail-Client/files/4465522/Multiple.Email.Code.txt)

**Comment by mobizt** [comment]
The difference between when you use the `imapData.setFetchUID` and `imapData.setSearchCriteria` is with `imapData.setFetchUID` is for fetch or read all the data included the attachments from a single message, while `imapData.setSearchCriteria` is for searching the message with the criteria and returns the message header only (no message body and attachment).

Why no body and attachment returning in search mode? It is because it may use a lot of memory and time to iterate through each message in the search result list, which not fit or suitable for the limited memory device, even it has flash memory. 

If you want to read multiple messages, you need to keep the UID list from the `imapData.setSearchCriteria` and use these UIDs in the list in the `imapData.setFetchUID` to read the whole data from each message. 

The latest update is for the ethernet problem fix.

**Comment by jawilson104** [comment]
Thanks again for the quick response.  A couple of more lines of code and I will be up and running.  Your answer was very clear.  Thanks again for your help.
