### ISSUE TITLE
private certificate

### ISSUE THREAD

**Issue by MarcEngrie** [mobizt/ESP32-Mail-Client#58]
Hi, 

I have a local SMTP server running using STARTTLS but with a private, self-generated certificate. I can send mails using Python scripts through smtplib and ssl. 
I can send mails using your library to public SMTP server (smpt.telenet.be) but sending to my local SMTP server it fails on the SSL certificate. 

15:08:20.883 -> Connecting to SMTP server...
15:08:20.883 -> [DEBUG] - INFO: connecting to SMTP server...
15:08:20.883 -> [DEBUG] - 192.168.1.42
15:08:20.883 -> [DEBUG] - 587
15:08:20.883 -> [DEBUG] - INFO: starting socket
15:08:20.883 -> [DEBUG] - INFO: connecting to Server...
15:08:20.883 -> [DEBUG] - INFO: server connected
15:08:20.883 -> [DEBUG] - INFO: begin STARTTLS handshake
15:08:21.951 -> [DEBUG] - 220 Oldies ESMTP SMTPBeamer v3.57
15:08:21.951 -> 
15:08:21.951 -> [DEBUG] - INFO: send SMTP command extended HELO
15:08:22.931 -> [DEBUG] - 250-Oldies
15:08:22.931 -> 
15:08:22.931 -> [DEBUG] - INFO: send STARTTLS protocol command
15:08:23.988 -> [DEBUG] - 250-ENHANCEDSTATUSCODES
15:08:23.988 -> 250-DSN
15:08:23.988 -> 250-PIPELINING
15:08:23.988 -> 250-8BITMIME
15:08:23.988 -> 250-SMTPUTF8
15:08:23.988 -> 250-PRIORITY
15:08:23.988 -> 250-CHUNKING
15:08:23.988 -> 250-STARTTLS
15:08:23.988 -> 250-SIZE
15:08:23.988 -> 250 XSBEAM30
15:08:23.988 -> 
15:08:23.988 -> [DEBUG] - INFO: seeding the random number generator
15:08:23.988 -> [DEBUG] - INFO: setting up the SSL/TLS structure...
15:08:23.988 -> [DEBUG] - INFO: setting hostname for TLS session...
15:08:23.988 -> [DEBUG] - INFO: performing the SSL/TLS handshake...
15:08:23.988 -> [DEBUG] - ERROR: SSL - An invalid SSL record was received
15:08:23.988 -> [DEBUG] - INFO: cleaning SSL connection

NB: in the Python library, there is a way to overcome this using this
 _create_unverified_https_context = ssl._create_unverified_context
and by starting TLS without context  server.starttls()

**Comment by mobizt** [comment]
The WiFiClientSecure failed in the SSL/TLS handshake process, which the issues related to the server and client.

ESP32 uses the mbedTLS library as SSL/TLS provider.

There is something that not match or agree between server and client (mbedTLS), which not concern with the library operation and can't help or fix by the library.

Here are the possible causes of SSL/TLS handshake failure
https://www.thesslstore.com/blog/tls-handshake-failed/

Python runs under Windows or Linux environment which the OpenSSL installed which different from an embedded device environment that uses mbedTLS. 

I close the issue because it can't solve by the library or code.

If OpenSSL installed, test your server with this command and get all the information during the communication process.

**openssl  s_client -connect your_host:your_server_port**
